name: build

on:
  push:
    branches: [ 'main' ]
    tags: [ '*' ]
  pull_request:
    branches: [ 'main' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.10

      - name: Install pipenv
        run: pip install pipenv

      - name: Lint
        run: _CI/scripts/lint.py

      - name: Test
        run: _CI/scripts/test.py

      - name: Build
        run: _CI/scripts/build.py

      - name: Upload built package
        uses: actions/upload-artifact@v3
        with:
          name: awsenergylabelercli-latest
          path: dist/awsenergylabelercli-*.tar.gz

  release:
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: release
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.10

      - name: Install pipenv
        run: pip install pipenv

      - name: Upload
        run: _CI/scripts/upload.py

        env:

          PYPI_UPLOAD_USERNAME: ${{ secrets.PYPI_UPLOAD_USERNAME }}
          PYPI_UPLOAD_PASSWORD: ${{ secrets.PYPI_UPLOAD_PASSWORD }}

  container_release:
    if: github.event_name == 'push'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: release
    steps:
      - name: Get version
        run: echo "RELEASE_VERSION=`cat .VERSION`" >> $GITHUB_ENV

      - name: Show current dir
        run: pwd

      - name: Show current directory listing
        run: ls -alh

      - name: Show parent directory
        run: ls -alh ..

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup gcloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
          
      - name: Configure docker for GCP
        run: gcloud auth configure-docker

      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: awsenergylabelercli-latest
      
      - name: Show current directory listing
        run: ls -alh

      - name: Build docker image 
        run:  docker build -t awsenergylabelercli .

      - name: Tag container for current version
        run: docker tag awsenergylabelercli gcr.io/perfect-period-356018/awsenergylabelercli:${RELEASE_VERSION}

      - name: Tag container as latest
        run: docker tag awsenergylabelercli gcr.io/perfect-period-356018/awsenergylabelercli:latest

      - name: Push to Google Container Registry as version
        run:  docker push gcr.io/perfect-period-356018/awsenergylabelercli:${RELEASE_VERSION}

      - name: Push to Google Container Registry as latest
        run:  docker push gcr.io/perfect-period-356018/awsenergylabelercli:latest